// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psekzfcpwjepdgbcyqqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZWt6ZmNwd2plcGRnYmN5cXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzA2MTIsImV4cCI6MjA2MjA0NjYxMn0.3_PmoGaV-07z1svYkObr6ksGULNloNEouEWmt7R258s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);